

try:
    print(a)
except Exception as e:
    print("something went wrong please try again later ")
    

print("hello")